# Generated by Django 3.1.4 on 2022-09-23 01:31

import counsellor.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=120, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=120, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('other_names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Names')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin Access')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('user_type', models.CharField(choices=[(counsellor.enums.UserType['STUDENT'], 'student'), (counsellor.enums.UserType['NON_STUDENT'], 'non_student'), (counsellor.enums.UserType['STAFF'], 'staff'), (counsellor.enums.UserType['NON_STAFF'], 'non_staff')], default=counsellor.enums.UserType['STUDENT'], max_length=25, verbose_name='User Type')),
                ('sex', models.CharField(choices=[(counsellor.enums.Gender['MALE'], 'male'), (counsellor.enums.Gender['FEMALE'], 'female'), (counsellor.enums.Gender['UNKNOWN'], 'unknown')], default=counsellor.enums.Gender['UNKNOWN'], max_length=20, verbose_name='Sex/Gender')),
                ('religion', models.CharField(choices=[(counsellor.enums.Religion['CHRISTIAN'], 'christian'), (counsellor.enums.Religion['MUSLIM'], 'muslim'), (counsellor.enums.Religion['TRADITIONAL'], 'traditional'), (counsellor.enums.Religion['OTHER'], 'other')], default=counsellor.enums.Religion['OTHER'], max_length=50, verbose_name='Religion')),
                ('marital_status', models.CharField(choices=[(counsellor.enums.MaritalStatus['MARRIED'], 'Married'), (counsellor.enums.MaritalStatus['SINGLE'], 'Single'), (counsellor.enums.MaritalStatus['SEPARATED'], 'Separated'), (counsellor.enums.MaritalStatus['DIVORCED'], 'Divorced'), (counsellor.enums.MaritalStatus['WIDOWED'], 'Widowed'), (counsellor.enums.MaritalStatus['WIDOWER'], 'Widower')], default=counsellor.enums.MaritalStatus['SINGLE'], max_length=50, verbose_name='Marital Status')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='phone')),
                ('show_name', models.BooleanField(choices=[(counsellor.enums.StringBoolChoices['YES'], 'yes'), (counsellor.enums.StringBoolChoices['NO'], 'no')], default=counsellor.enums.StringBoolChoices['NO'])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Cousellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=120, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('other_names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Names')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin Access')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('sex', models.CharField(choices=[(counsellor.enums.Gender['MALE'], 'male'), (counsellor.enums.Gender['FEMALE'], 'female'), (counsellor.enums.Gender['UNKNOWN'], 'unknown')], default=counsellor.enums.Gender['UNKNOWN'], max_length=20, verbose_name='Sex/Gender')),
                ('phone', models.CharField(max_length=16, unique=True, verbose_name='phone')),
                ('available', models.BooleanField(default=False, verbose_name='last_login')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'counsellor',
                'verbose_name_plural': 'counsellors',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=25, null=True, verbose_name='Registration Number')),
                ('programme', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=100, null=True, verbose_name='Programme')),
                ('department', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=100, null=True, verbose_name='Faculty/Department')),
                ('level', models.CharField(blank=True, choices=[(counsellor.enums.Level['YEAR_100'], 100), (counsellor.enums.Level['YEAR_200'], 200), (counsellor.enums.Level['YEAR_300'], 300), (counsellor.enums.Level['YEAR_400'], 400), (counsellor.enums.Level['YEAR_500'], 500), (counsellor.enums.Level['YEAR_600'], 600), (counsellor.enums.Level['YEAR_700'], 700), (counsellor.enums.Level['YEAR_800'], 800)], default=None, help_text="Fill this field if you're a student", max_length=10, null=True, verbose_name='Level')),
                ('residence', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=100, null=True, verbose_name='Hall of Res./Hostel')),
                ('home_phone', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=10, null=True, verbose_name='Home Phone')),
                ('worker', models.CharField(blank=True, choices=[(counsellor.enums.StringBoolChoices['YES'], 'yes'), (counsellor.enums.StringBoolChoices['NO'], 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=10, null=True, verbose_name='Worker')),
                ('work_type', models.CharField(blank=True, help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=100, null=True, verbose_name='Type Of Work')),
                ('organization', models.CharField(blank=True, help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=100, null=True, verbose_name='Name of Organization')),
                ('emergency_person', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Emergency Contact Name')),
                ('emergency_contact', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Emergency Contact Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('referrer', models.TextField(blank=True, help_text='Whom may we thank for referring you?', null=True, verbose_name='Referrer')),
                ('prev_counselling', models.CharField(blank=True, choices=[(counsellor.enums.StringBoolChoices['YES'], 'yes'), (counsellor.enums.StringBoolChoices['NO'], 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Any previous counselling on present concern?', max_length=10, null=True, verbose_name='Previous Counselling')),
                ('on_medication', models.CharField(blank=True, choices=[(counsellor.enums.StringBoolChoices['YES'], 'yes'), (counsellor.enums.StringBoolChoices['NO'], 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Are you on any pescribed medications?', max_length=10, null=True, verbose_name='On Prescribed Medication')),
                ('guardian', models.CharField(blank=True, help_text="If you're not a student of UCC and you are below 18 years, provide particulars for parent/guardian", max_length=100, null=True, verbose_name='Guardian Name')),
                ('guardian_phone', models.CharField(blank=True, help_text="If you're not a student of UCC and you are below 18 years, provide particulars for parent/guardian", max_length=10, null=True, verbose_name='Guardian Phone')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cousellor_consents', to='counsellor.cousellor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
