# Generated by Django 3.1.4 on 2022-09-23 02:59

import counsellor.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=120, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=120, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('other_names', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Names')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin Access')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('user_type', models.CharField(choices=[('STUDENT', 'student'), ('NON_STUDENT', 'non_student'), ('STAFF', 'staff'), ('NON_STAFF', 'non_staff')], default=counsellor.enums.UserType['STUDENT'], max_length=25, verbose_name='User Type')),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('UNKNOWN', 'unknown')], default=counsellor.enums.Gender['UNKNOWN'], max_length=20, verbose_name='Sex/Gender')),
                ('religion', models.CharField(choices=[('CHRISTIAN', 'christian'), ('MUSLIM', 'muslim'), ('TRADITIONAL', 'traditional'), ('OTHER', 'other')], default=counsellor.enums.Religion['OTHER'], max_length=50, verbose_name='Religion')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('WIDOWER', 'Widower')], default=counsellor.enums.MaritalStatus['SINGLE'], max_length=50, verbose_name='Marital Status')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('show_name', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counsellor.user')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'counsellor',
                'verbose_name_plural': 'counsellors',
            },
            bases=('counsellor.user',),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=25, null=True, verbose_name='Registration Number')),
                ('programme', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=100, null=True, verbose_name='Programme')),
                ('department', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=100, null=True, verbose_name='Faculty/Department')),
                ('level', models.CharField(blank=True, choices=[('YEAR_100', 100), ('YEAR_200', 200), ('YEAR_300', 300), ('YEAR_400', 400), ('YEAR_500', 500), ('YEAR_600', 600), ('YEAR_700', 700), ('YEAR_800', 800)], default=None, help_text="Fill this field if you're a student", max_length=10, null=True, verbose_name='Level')),
                ('residence', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=100, null=True, verbose_name='Hall of Res./Hostel')),
                ('home_phone', models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=10, null=True, verbose_name='Home Phone')),
                ('worker', models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=10, null=True, verbose_name='Worker')),
                ('work_type', models.CharField(blank=True, help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=100, null=True, verbose_name='Type Of Work')),
                ('organization', models.CharField(blank=True, help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=100, null=True, verbose_name='Name of Organization')),
                ('emergency_person', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Emergency Contact Name')),
                ('emergency_contact', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Emergency Contact Phone')),
                ('referrer', models.TextField(blank=True, help_text='Whom may we thank for referring you?', null=True, verbose_name='Referrer')),
                ('prev_counselling', models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Any previous counselling on present concern?', max_length=10, null=True, verbose_name='Previous Counselling')),
                ('on_medication', models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Are you on any pescribed medications?', max_length=10, null=True, verbose_name='On Prescribed Medication')),
                ('guardian', models.CharField(blank=True, help_text="If you're not a student of UCC and you are below 18 years, provide particulars for parent/guardian", max_length=100, null=True, verbose_name='Guardian Name')),
                ('guardian_phone', models.CharField(blank=True, help_text="If you're not a student of UCC and you are below 18 years, provide particulars for parent/guardian", max_length=10, null=True, verbose_name='Guardian Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cousellor_consents', to='counsellor.counsellor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
