# Generated by Django 3.1.4 on 2022-11-18 02:30

import counsellor.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='emergency_contact',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text="If you're not a student of UCC and you are below 18 years, provide particulars for parent/guardian", max_length=15, null=True, verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='on_medication',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Are you on any pescribed medications?', max_length=15, null=True, verbose_name='On Prescribed Medication'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='prev_counselling',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Any previous counselling on present concern?', max_length=15, null=True, verbose_name='Previous Counselling'),
        ),
    ]
