# Generated by Django 3.1.4 on 2022-09-23 09:10

import counsellor.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'married'), ('SINGLE', 'single'), ('SEPARATED', 'separated'), ('DIVORCED', 'divorced'), ('WIDOWED', 'widowed'), ('WIDOWER', 'widower')], default=counsellor.enums.MaritalStatus['SINGLE'], max_length=50, verbose_name='Marital Status'),
        ),
    ]
