# Generated by Django 3.1.4 on 2022-09-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0002_auto_20220923_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/counselors/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/client/'),
        ),
    ]
