# Generated by Django 3.1.4 on 2022-11-18 02:34

import counsellor.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0002_auto_20221118_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='emergency_contact',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text="If you're not a student of UCC and you are below 18 years, provide particulars for parent/guardian", max_length=50, null=True, verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='home_phone',
            field=models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=50, null=True, verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='level',
            field=models.CharField(blank=True, choices=[('YEAR_100', 100), ('YEAR_200', 200), ('YEAR_300', 300), ('YEAR_400', 400), ('YEAR_500', 500), ('YEAR_600', 600), ('YEAR_700', 700), ('YEAR_800', 800)], default=None, help_text="Fill this field if you're a student", max_length=50, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='on_medication',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Are you on any pescribed medications?', max_length=50, null=True, verbose_name='On Prescribed Medication'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='prev_counselling',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text='Any previous counselling on present concern?', max_length=50, null=True, verbose_name='Previous Counselling'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='registration_number',
            field=models.CharField(blank=True, default=None, help_text="Fill this field if you're a student", max_length=50, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='worker',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], default=counsellor.enums.StringBoolChoices['NO'], help_text="Fill this field if you're a non-ucc-student/staff/non-staff", max_length=50, null=True, verbose_name='Worker'),
        ),
    ]
