# Generated by Django 3.1.4 on 2022-09-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0004_auto_20220923_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellingtype',
            options={'verbose_name': 'counselling type', 'verbose_name_plural': 'counselling types'},
        ),
    ]
