# Generated by Django 3.1.4 on 2022-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0005_auto_20220923_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingtype',
            name='type',
            field=models.CharField(max_length=100, unique=True, verbose_name='Type'),
        ),
    ]
