# Generated by Django 3.1.4 on 2022-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0006_auto_20220923_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='referrer',
            field=models.CharField(blank=True, help_text='Whom may we thank for referring you?', max_length=100, null=True, verbose_name='Referrer'),
        ),
    ]
