# Generated by Django 3.1.4 on 2022-09-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0007_auto_20220923_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='show_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
