# Generated by Django 3.1.4 on 2022-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0008_auto_20220924_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=4, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'available day',
                'verbose_name_plural': 'available days',
            },
        ),
        migrations.AddField(
            model_name='counsellor',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Short Biography'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='availability',
            field=models.ManyToManyField(related_name='counsellors_available', to='counsellor.AvailableDay'),
        ),
    ]
