# Generated by Django 3.1.4 on 2022-09-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0009_auto_20220926_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableday',
            options={'ordering': ['id'], 'verbose_name': 'available day', 'verbose_name_plural': 'available days'},
        ),
    ]
