# Generated by Django 3.1.4 on 2022-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0010_auto_20220926_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Short Biography'),
        ),
    ]
