# Generated by Django 3.1.4 on 2022-09-26 23:07

import counsellor.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0011_auto_20220926_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('MS', 'Ms'), ('DR', 'Dr')], default=counsellor.enums.Honorifics['MR'], max_length=5, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='availability',
            field=models.ManyToManyField(related_name='counsellor_days_available', to='counsellor.AvailableDay'),
        ),
    ]
