# Generated by Django 3.1.4 on 2022-11-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0013_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meeting ID'),
        ),
    ]
