# Generated by Django 3.1.4 on 2022-11-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0014_booking_meet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='counselor',
            new_name='counsellor',
        ),
    ]
