# Generated by Django 3.1.4 on 2022-11-16 11:42

import counsellor.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0015_auto_20221116_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('VIRTUAL', 'VIRTUAL'), ('MEET_IN_PERSON', 'MEET_IN_PERSON')], default=counsellor.enums.BookingType['VIRTUAL'], max_length=20, verbose_name='Booking Type'),
        ),
    ]
