# Generated by Django 3.1.4 on 2022-11-16 12:06

import counsellor.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0017_auto_20221116_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='counselor',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('VIRTUAL', 'VIRTUAL'), ('MEET_IN_PERSON', 'MEET IN PERSON')], default=counsellor.enums.BookingType['VIRTUAL'], max_length=20, verbose_name='Booking Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('New', 'New'), ('Completed', 'Completed')], default=counsellor.enums.BookingStatus['New'], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to=settings.AUTH_USER_MODEL),
        ),
    ]
