# Generated by Django 3.1.4 on 2022-11-16 12:09

import counsellor.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0018_auto_20221116_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('VIRTUAL', 'VIRTUAL MEETING'), ('MEET_IN_PERSON', 'MEET IN PERSON')], default=counsellor.enums.BookingType['VIRTUAL'], max_length=20, verbose_name='Booking Type'),
        ),
    ]
